---
- name: Install pip3
  apt:
    name: python3-pip

- name: Install git
  apt:
    name: git

- name: Locales
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive

- name: Pip install packages
  command: "{{ item }}"
  with_items:
    - pip3 install tweepy
    - pip3 install couchdb
    - pip3 install nltk
    - pip3 install sklearn
    - pip3 install shapely
    - pip3 install geopandas
    - pip3 install scipy


- name: clone git project
  git:
    repo: "https://github.com/zjw93615/COMP90024_Team26.git"
    dest: /home/ubuntu/COMP90024_Team26

- name: Run tweepySearch.py
  vars:
    HOST_COUNT: "{{ groups['crawler'] | length }}"
    current_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
  command: "python3 tweepySearch.py -t {{ HOST_COUNT }} -r {{ current_index }}"
  args:
    chdir: /home/ubuntu/COMP90024_Team26/Python_code/Final/Tweet_Crawler_Final/
  async: 5
  poll: 0

- name: Run tweepyStream.py
  vars:
    HOST_COUNT: "{{ groups['crawler'] | length }}"
    current_index: "{{ ansible_play_batch.index(inventory_hostname) }}"
  command: "python3 tweepyStream.py -t {{ HOST_COUNT }} -r {{ current_index }}"
  args:
    chdir: /home/ubuntu/COMP90024_Team26/Python_code/Final/Tweet_Crawler_Final/
  async: 5
  poll: 0






