---
- name: Install pip3
  apt:
    name: python3-pip

- name: Install git
  apt:
    name: git

# - name: Pip config
#   command: sudo export LC_ALL="en_US.UTF-8"
#   ignore_errors: yes

# - name: Pip config
#   command: export LC_CTYPE="en_US.UTF-8"
#   ignore_errors: yes

- name: Locales
  command: "{{ item }}"
  with_items:
    - export LC_ALL="en_US.UTF-8"
    - export LC_CTYPE="en_US.UTF-8"
    - dpkg-reconfigure locales -f noninteractive

- name: Pip install packages
  command: "{{ item }}"
  with_items:
    - pip3 install tweepy
    - pip3 install couchdb
    - pip3 install nltk
    - pip3 install sklearn
    - pip3 install shapely
    - pip3 install geopandas
    - pip3 install scipy


- name: clone git project
  git:
    repo: "https://github.com/zjw93615/COMP90024_Team26.git"
    dest: /home/ubuntu/COMP90024_Team26

- name: Run tweepySearch.py
  command: nohup python3 tweepySearch.py </dev/null >/dev/null 2>&1 &
  args:
    chdir: /home/ubuntu/COMP90024_Team26/Python_code/Final/Tweet_Crawler_Final/

- name: Run tweepyStream.py
  command: nohup python3 tweepyStream.py </dev/null >/dev/null 2>&1 &
  args:
    chdir: /home/ubuntu/COMP90024_Team26/Python_code/Final/Tweet_Crawler_Final/







