---
# This playbook deploys a simple standalone Tomcat 7 server.

# - hosts: crawler
#   sudo: yes

#   roles:
#     - mount
#     - couchdb
#     - crawler

# - hosts: preprocess
#   sudo: yes

#   roles:
#     - mount
#     - couchdb
#     - preprocess

- hosts: web_server
  sudo: yes

  roles:
    # - mount
    # - couchdb
    - webserver