---
- name: Make file system
  filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: Creates directory
  file: path=/database state=directory

- name: Mount file
  mount:
    path: /database
    src: /dev/vdb
    fstype: ext4
    state: mounted